#!/usr/bin/env bash
# 3x-findroot -- find the root of the current experiment repository
# Usage: 3x findroot
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

is-root() { [ -d .3x -a -d program -a -d input -a -d output ]; }

if [ -n "${_3X_ROOT:-}" ]; then
    if [ -d "$_3X_ROOT" ] && cd "$_3X_ROOT" && is-root; then
        pwd -P
    else
        error "$_3X_ROOT: \$_3X_ROOT does not point to an experiment repository"
    fi
else
    OPWD=$PWD
    while ! is-root && [ "$PWD" != / ]; do
        cd ..
    done
    if is-root; then
        pwd -P
    else
        error "$OPWD: Not inside an experiment repository"
    fi
fi
