#!/usr/bin/env bash
# 3x-hack -- run commands inside 3X's environment
# > 3x hack COMMAND [ARG]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- "$SHELL" -i

exec "$@"
