#!/usr/bin/env bash
# archive -- De-duplicate given FILEs with the hardlink copies in REPO
# 
# > archive REPO FILE...
# 
# If there's a file already in the REPO with the same hash, FILE will be
# replaced as a hardlink to it.  Otherwise, a new hardlink of FILE will be
# created in the REPO, named after its hash in the REPO, e.g.,
# REPO/9a/da/8506c0746cb36bb250449c5322590748a924.  The SHA1 hash for each FILE
# is computed with `git hash-object`.
# 
# All the hardlinked files will be marked read-only, i.e., have writable
# permission cleared after they are archived.
# 
# When a directory is archived, all the files within that directory will be
# archived first, then the directories will be marked read-only.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-24
exec nodups archive "$@"
