#!/usr/bin/env bash
# be-quiet -- Check if logging is suppressed by $EXPKIT_LOGLVL
# Usage: be-quiet [+-ADJUSTMENT]
#   Use positive ADJUSTMENT if the caller is thought to be handling a subtask.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
(( EXPKIT_LOGLVL += 1 - ${1:-0} ))
[[ $SHLVL > $EXPKIT_LOGLVL ]]
