#!/usr/bin/env bash
# color-marked-row -- decorate the first word of marked line with color
# 
# > color-marked-row MARK [ANSI_COLOR_CODE]
# 
# For ANSI_COLOR_CODE, see: http://en.wikipedia.org/wiki/ANSI_escape_code#Colors
# Default color is green, i.e., ANSI_COLOR_CODE being: 0;32
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-14
set -eu
if [ -t 1 ]; then
    if _3X_COLOR=false; ${_3X_COLOR:-true}; then
        [ $# -gt 0 ] || usage "$0" "Missing MARK"
        mark=$(printf %q "$1")
        color=${2:-0;32} # default to green color
        column -t |
        sed '/^'"$mark"' / s/^\('"$mark"' *\)\([^ ]*\)/\1'$'\e['"$color"'m''\2'$'\e[0m''/'
    else
        exec column -t
    fi
else
    exec cat
fi
