#!/usr/bin/env bash
# exp-findroot -- find the root of the current experiment repository
# Usage: exp findroot
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

is-root() { [ -d .exp -a -d condition -a -d program ]; }

if [ -n "${EXPROOT:-}" ]; then
    if [ -d "$EXPROOT" ] && cd "$EXPROOT" && is-root; then
        echo "$EXPROOT"
    else
        error "$EXPROOT: \$EXPROOT does not point to an experiment repository"
    fi
else
    OPWD=$PWD
    while ! is-root && [ "$PWD" != / ]; do
        cd ..
    done
    if is-root; then
        pwd
    else
        error "$OPWD: Not inside an experiment repository"
    fi
fi
