#!/usr/bin/env bash
# serialOnEachLine -- add a serial number to each line
# 
# > serialOnEachLine INPUT [START] >OUTPUT
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-14
set -eu

f=$1
START=${2:-1}
awk <"$f" '
    BEGIN {seq='$START'}
    {printf "%s #%d\n", $0, seq++}
'
