#!/usr/bin/env bash
# super -- invoke the parent command overriden by the current one
# Usage: super COMMAND [ARG]...
# 
# A typical usage from shell would be as:
# > super "$0" "$@"
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-10
set -eu
[ $# -gt 0 ] || usage "$0" "No COMMAND specified"
this=$1; shift
super=$(type -a -p "${this##*/}" |
    grep -A1 -xF "$this" |
    { set -e; read; read -r x; echo "$x"; })
let SHLVL--
exec "$super" "$@"
