#!/usr/bin/env bash
# unarchive -- Remove hardlink copies of given FILEs from the REPO
# 
# > unarchive REPO FILE...
# 
# Any hardlink copies that may solely remain in the REPO if `rm -f FILE...`
# would be run will be removed.  Note that the given FILEs are not removed by
# this command.
# 
# The SHA1 hash for each FILE is computed with `git hash-object` as done in
# `archive`.
# 
# When a directory is unarchived, all its subdirectories marked read-only will
# become read-writable.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-06
exec nodups unarchive "$@"
