#!/usr/bin/env bash
# ssh-cluster/refresh-all -- reflect cluster status to queue
# 
# > . find-runner.sh -
# > refresh-all _3X_WORKER_DIR
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-25
set -eu

_3X_WORKER_DIR=$1; shift

. ssh-cluster-runner.sh

cd "$_3X_WORKER_DIR"

# fetch which runs have finished
isRemoteFinished() {
    local splitRemote=$1
    [[ -e "$splitRemote" && ! -e "$splitRemote".finished ]] || return 0
    local split=${splitRemote%.remote}
    local remote=$(cat $splitRemote)
    runner-msg +1 "checking runs at $remote"
    ssh-3x-remote $remote is-finished
}
eachInParallel isRemoteFinished runSplit.*.remote
waitAll
