#!/usr/bin/env bash
# ssh-cluster/stop-all -- stop all running runs on the cluster via ssh
# 
# > . find-runner.sh -
# > stop-all _3X_WORKER_DIR
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-24
set -eu

_3X_WORKER_DIR=$1; shift

. ssh-cluster-runner.sh

cd "$_3X_WORKER_DIR"

# stop runs at each remote
stopRuns() {
    local splitRemote=$1
    [[ -e "$splitRemote" ]] || return 0
    local split=${splitRemote%.remote}
    local remote=$(cat $splitRemote)
    runner-msg "stopping and cleaning up runs at $remote"
    ssh-3x-remote $remote stop
    lsUnfinishedRunsIn serial $split |
    xargs queue mark-as PLANNED
    mv -f $splitRemote $splitRemote.clean
}
eachInParallel stopRuns  runSplit.*.remote
waitAll

if sharedRemote=$(getSharedRemoteURL); then
    runner-msg "cleaning up remote repository"
    ssh-3x-remote $sharedRemote cleanup
fi

cd - >/dev/null
rm -rf "$_3X_WORKER_DIR"
