#!/usr/bin/env bash
# run-all -- run given runs
# Usage:
# > run-all FILE_LISTING_ALL_RUNS
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-09-23
set -eu

error "$_3X_RUNNER/run-all: Not implemented"
