#!/usr/bin/env bash
# judge-state-of-run -- print the final state of run based on its record
# Usage:
# > _3X_RUN=... judge-state-of-run
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-09-25
set -eu

cd "$_3X_ROOT/$_3X_RUN"

state=DONE
# it is a user program failure when the output isn't complete
[[ ! -s outputs.failed && -s output ]] ||
    state=FAILED

# record the run in the "done" list with its state
echo $state
