#!/usr/bin/env bash
# queue-changed -- Handle the modification event of the current queue
# 
# > . find-runner.sh -
# > setsid queue-changed
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-16
set -eu

error "$_3X_RUNNER/queue-changed: Not implemented"
