#!/usr/bin/env bash
# > 3x stop
# Stops executing runs in current queue.
#
# queue-stop -- stop execution of runs in current queue
# 
# > . find-runner.sh -
# > setsid queue-stop
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-16
set -eu

error "$_3X_RUNNER/queue-stop: Not implemented"
