#!/usr/bin/env bash
# queue-sync -- Synchronize repository with what happened at the target
# 
# > . find-runner.sh -
# > setsid queue-sync
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-16
set -eu

true #error "$_3X_RUNNER/queue-sync: Not implemented"
