#!/usr/bin/env bash
# run -- process a run
# See runner.sh for extending and overriding base runners behavior.
# 
# Usage:
# > . runner.sh
# ...
# > _3X_RUNNER_DIR=... \
# > _3X_RUN=... \
# > run NAME=VALUE...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-11
set -eu

[ $# -gt 0 ] || usage "$0" "At least one NAME=VALUE pairs must be given"

# store the run regardless of whether execution finishes or aborts
cleanup() {
    local c=$?
    msg "$_3X_RUN: Storing"
    run.store
    return $c
}
trap cleanup EXIT

# assemble the run
msg "$_3X_RUN: Assembling run $*"
run.assemble "$@" ||
    error "$_3X_RUN: Assembly failed"

# execute it
msg "$_3X_RUN: Executing run $*"
run.execute
