#!/usr/bin/env bash
# > 3x target TARGET info
# Displays information of a target execution environment, named TARGET.
#
#
# target-info -- display target info
# > target-info TARGET
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-06-26
set -eu

Target=$1
cd "$_3X_ROOT"/run/target/"$Target"

echo "## run/target/$Target"
echo "# type:"
echo "$_3X_RUNNER"
