#!/usr/bin/env bash
# 3x-edit -- edit plan for REMAINING runs of an experiment batch
# Usage: 3x edit BATCH
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-22
set -eu

[ $# -ge 1 ] || usage "$0" "BATCH must be given"

_3X_ROOT=$(3x-findroot)

batch=$1; shift
prePlanned=${1:-}

# figure out which batch we are talking about
batchpath=$(readlink -f "$batch")
[[ $batchpath == $_3X_ROOT/run/batch/* ]] || error "Not a path to a batch: $batch"
export _3X_BATCH=${batchpath#$_3X_ROOT/}

newPlan=plan.editing

# prepare the plan file for editing
if ! [ -e "$newPlan" ]; then
    if [ -r "$prePlanned" ]; then
        cp "$prePlanned" "$_3X_ROOT/$_3X_BATCH/$newPlan"
        EDITOR=true
    else
        3x-status "$_3X_BATCH" | grep REMAINING |
        sed 's/^[^[:space:]]*[[:space:]]*/3x run  /; s/[[:space:]]*[^[:space:]]*$//' >"$_3X_ROOT/$_3X_BATCH/$newPlan"
    fi
fi

cd "$_3X_ROOT/$_3X_BATCH"

# let user edit the plan and update the batch once it gets modified
if edit $newPlan $newPlan.in-progress; then
    # TODO sanity check of $newPlan
    # make sure nobody else changes the status of runs in this batch
    lockproc remaining.lock grab
    trap "lockproc remaining.lock release" EXIT
    # find out the serials of runs which are still REMAINING
    3x-status "$_3X_BATCH" | grep REMAINING |
    sed 's/[[:space:]]*[^[:space:]]*$//; s/^.*#/#/' >$newPlan.serials
    # replace the remaining file with newly planned runs still REMAINING
    grep -F -f $newPlan.serials <$newPlan >remaining
    rm -f $newPlan.serials
    # TODO having dedup of serials in the remaining might be a good idea
    # clean up any running.* that's not actually RUNNING, therefore REMAINING,
    # and could have been pushed to later in the new plan
    for r in running.*/; do
        [ -d "$r" ] || continue
        ! lockproc "$r"/lock alive || continue
        rm -rf "$r"
    done
    msg +0 -n "Updated plan of $(wc -l <remaining) REMAINING runs in "
    echo "$_3X_BATCH"
else
    msg "Canceled editing $_3X_BATCH"
fi
rm -f $newPlan
