#!/usr/bin/env bash
# exp-status -- display status of an experiment batch
# Usage: exp status BATCH
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-14
set -eu

[ $# -eq 1 ] || usage "$0" "Exactly one BATCH must be given"

Batch=$1

: ${EXPROOT:=$(exp-findroot)}
cd "$EXPROOT/$Batch"

{
    hasProgress=false

    PREFIXPATT='^exp[ 	]*run[ 	]*'
    # runs already finished
    if [ -r done ]; then
        sed "s:$PREFIXPATT:DONE :" <"done" |
        perl -ne '
            use strict; use Cwd "abs_path";
            my ($line, $serial) = /^(.*#)(\d+)$/;
            my $runpath = abs_path("runs/$serial");
            $runpath =~ s#.*/run/#run/#;
            printf "%s%s %s\n", $line, $serial, $runpath;
            '
        hasProgress=true
    fi

    # runs still running
    for running in running.*; do
        [ -d "$running" ] || continue
        [ -s "$running"/cmdln ] || continue
        # see if it's actually running
        state=RUNNING
        lockproc "$running"/lock alive || state=REMAINING
        line=$(sed "s:$PREFIXPATT:$state :" <"$running"/cmdln)
        # TODO add column for the actual runId?
        case $state in
            RUNNING)
                run=$(readlink -f "runs/$(sed 's:.*#::' <"$running"/cmdln)")
                run=${run#$EXPROOT/}
                line+=" $run"
                ;;
        esac
        echo "$line"
        hasProgress=true
    done

    # runs yet to be run
    if [ -r remaining ]; then
        sed "s:$PREFIXPATT:REMAINING :; s:$: ?:" <"remaining"
        hasProgress=true
    fi

    # if there's only a plan, show them as remaining
    if ! $hasProgress; then
        serialOnEachLine "plan" |
        sed "s:$PREFIXPATT:REMAINING :; s:$: ?:"
    fi
} | column -t
