#!/usr/bin/env bash
# exp-start -- start an experiment batch
# Usage: exp start BATCH
#        exp start [PROGRAM] [NAME[=VALUE[,VALUE]...]]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-07
set -eu

[ $# -ge 1 ] || usage "$0" "At least the BATCH must be given"

: ${EXPROOT:=$(exp-findroot)}

batch=$1

# figure out which batch we are talking about
if [ $# -eq 1 -a -d "$batch" ]; then
    batchpath=$(readlink -f "$batch")
    [[ $batchpath == $EXPROOT/run/batch/* ]] || error "Not a path to a batch: $batch"
    shift
    EXPBATCH=${batchpath#$EXPROOT/}
else
    EXPBATCH=$(new-batch-id)
    EXPBATCH=$EXPBATCH \
    EXPBATCH_STARTING=true \
        exp-plan "$@"
fi
export EXPBATCH

cd "$EXPROOT/$EXPBATCH"

# launch batch-loop in a separate process group, using bash -i, so we can kill
# all related processes together later.
exec setsid batch-loop
