#!/usr/bin/env bash
# exp-stop -- stop an experiment batch
# Usage: exp stop BATCH [WORKER]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-17
set -eu

[ $# -ge 1 ] || usage "$0" "BATCH must be given"

EXPROOT=$(exp-findroot)

# figure out which batch we are talking about
batch=$1; shift
[ -d "$batch" ] || error "$batch: No such file"
batchpath=$(readlink -f "$batch")
[[ $batchpath == $EXPROOT/run/batch/* ]] || error "Not a path to a batch: $batch"
EXPBATCH=${batchpath#$EXPROOT/}
export EXPBATCH

cd "$EXPROOT/$EXPBATCH"

# collect the handles of workers
if [ $# -gt 0 ]; then
    handles=()
    for workerId; do
        handle=worker-"$workerId".lock
        [ -e "$handle" ] || error "No such worker #$workerId" || continue
        handles+=("$handle")
    done
    set -- "${handles[@]}"
else
    set -- worker-*.lock running.*/lock
fi

# and stop the workers
for handle; do
    [ -e "$handle" ] || continue
    lockproc "$handle" kill
done
