#!/usr/bin/env bash
# exp-gui -- start ExpKit GUI
# Usage: exp gui [start [PORT]]
#        exp gui stop
#        exp gui watch
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-11
set -eu
shopt -s extglob

defaultPort=38917
host=$(hostname -f)

EXPROOT=$(exp-findroot)
export EXPROOT

# make sure we don't go into an editor
export EDITOR=true VISUAL=true

cd "$EXPROOT"

mkdir -p .exp/gui
portfile=.exp/gui/port
logfile=.exp/gui/log
pidfile=.exp/gui/pid
get-pid() { ps -o pid= -p $(cat $pidfile); } 2>/dev/null

cmd=${1:-start}
[ $# -eq 0 ] || shift
case $cmd in
    start)
        pids=$(get-pid || true)
        port=$(cat $portfile 2>/dev/null || true)
        launchNew=false
        if [ -z "$pids" ]; then
            # use given port or reuse the last port or the default
            port=${1:-${port:-$defaultPort}}
            launchNew=true
        else
            msg "ExpKit GUI already running at http://$host:$port/"
            if [ $# -eq 1 ] && [ "$1" != "$port" ]; then
                # launch another GUI on different port
                port=$1
                launchNew=true
            fi
        fi
        if $launchNew; then
            # fail or find unused one if port is already in use
            if nc -z localhost $port &>/dev/null; then
                [ $# -eq 0 ] ||
                    error "Cannot start GUI at port $port: already in use"
                # determine unused port automatically, by keep incrementing it
                let ++port
                while nc -z localhost $port &>/dev/null; do
                    let ++port
                    # but never exceed the max port
                    [[ $port -lt 65536 ]] || error "Cannot start GUI, specify an available port number"
                done
            fi
            url="http://$host:$port/"
            # launch server
            python_site_dir="$GUIDIR"/server/python-packages
            PATH="$python_site_dir:$PATH" \
            PYTHONPATH="$python_site_dir${PYTHONPATH:+:$PYTHONPATH}" \
            setsid node "$GUIDIR"/server/expkit-gui.js $port \
                </dev/null >$logfile 2>&1 &
            pid=$!
            # record pid, port
            pids="$pid $(get-pid || true)"
            echo $pids >$pidfile
            echo $port >$portfile
            msg "ExpKit GUI started at $url"
        else
            url="http://$host:$port/"
        fi
        # watch log if requested
        be-quiet +1 || exp-gui watch &
        # and launch web browser on known platforms
        case $(uname) in
            Darwin) # Mac
                until nc -z localhost $port &>/dev/null; do sleep 0.1; done
                open "$url"
                ;;
        esac
        trap "kill -TERM \$(for pid in $pids; do echo -\$pid; done)" INT QUIT TERM
        wait
        ;;

    watch)
        # watch log
        pids=($(get-pid)) || error "ExpKit GUI not running"
        pid=${pids[0]}
        exec tail -qF $logfile --pid=$pid 2>/dev/null
        ;;

    stop)
        pids=$(get-pid) || error "ExpKit GUI not running"
        kill -TERM $(for pid in $pids; do echo -$pid; done)
        mv -f $logfile $logfile.0
        rm -f $pidfile
        msg "ExpKit GUI stopped"
        ;;

    # when it looks like a port number, do start instead of complaining
    +([0-9]))
        exec exp-gui start $cmd "$@"
        ;;

    *)
        usage "$0" "$cmd: Unknown command"
        ;;
esac
