#!/usr/bin/env bash
# exp-gui -- start ExpKit GUI
# Usage: exp gui [start [PORT]]
#        exp gui stop
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-11
set -eu

defaultPort=38917
host=$(hostname -f)

: ${EXPROOT:=$(exp-findroot)}
export EXPROOT

cd "$EXPROOT"

mkdir -p .exp/gui
portfile=.exp/gui/port
logfile=.exp/gui/log
pidfile=.exp/gui/pid
get-pid() { ps -o pid= -p $(cat $pidfile); } 2>/dev/null

cmd=${1:-start}
[ $# -eq 0 ] || shift
case $cmd in
    start)
        pid=$(get-pid || true)
        port=$(cat $portfile 2>/dev/null)
        launchNew=false
        if [ -z "$pid" ]; then
            # use given port or reuse the last port or the default
            port=${1:-${port:-$defaultPort}}
            launchNew=true
        else
            msg "ExpKit GUI already running at http://$host:$port/"
            if [ $# -eq 1 ] && [ "$1" != "$port" ]; then
                # launch another GUI on different port
                port=$1
                launchNew=true
            fi
        fi
        url="http://$host:$port/"
        if $launchNew; then
            # fail if port is already in use
            if nc -z $host $port; then
                [ $# -eq 0 ] ||
                    error "Cannot start GUI at port $port: already in use"
                # TODO determine unused port automatically
            fi
            # launch server
            node "$GUIDIR"/server/expkit-gui.js $port \
                </dev/null >$logfile 2>&1 &
            pid=$!
            # record pid, port
            echo $pid >$pidfile
            echo $port >$portfile
            msg "ExpKit GUI started at $url"
        fi
        # watch log if requested
        be-quiet +1 || exp-gui watch &
        # and launch web browser on known platforms
        case $(uname) in
            Darwin) # Mac
                until nc -z $host $port; do sleep 0.1; done
                open "$url"
                ;;
        esac
        wait
        ;;

    watch)
        # watch log
        pid=$(get-pid) || error "ExpKit GUI not running"
        exec tail -qF $logfile --pid=$pid 2>/dev/null
        ;;

    stop)
        pid=$(get-pid) || error "ExpKit GUI not running"
        kill -TERM $pid
        mv -f $logfile $logfile.0
        rm -f $pidfile
        msg "ExpKit GUI stopped"
        ;;
esac
