#!/usr/bin/env python
# watch-filesystem-events -- Monitor filesystem events and log
# Usage: PYTHONUNBUFFERED=true watch-filesystem-events PATH [IGNORE_PATTERN]...
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2014-01-07

import sys, time
from watchdog.observers import Observer
from watchdog.events import PatternMatchingEventHandler

class Handler(PatternMatchingEventHandler):
    def on_any_event(self, event):
        print >>sys.stderr, "%s %s" % (event.event_type, event.src_path)
        print "%s %s" % (event.event_type, event.src_path)

path = sys.argv[1] if len(sys.argv) > 1 else '.'
ignore_patterns = sys.argv[2:] if len(sys.argv) > 2 else None

event_handler = Handler(ignore_patterns=ignore_patterns)
observer = Observer()
observer.schedule(event_handler, path, recursive=True)
observer.start()
try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    observer.stop()
observer.join()
