#!/usr/bin/env bash
# 3x-assemble -- assemble an experiment with given parameters
# 
# > 3x assemble OUTPUTDIR [NAME=VALUE]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -ge 1 ] || usage "$0" "At least OUTPUTDIR must be given"

_3X_WD=$1; shift

_3X_ROOT=$(3x-findroot)

# create the OUTPUTDIR with a working directory
mkdir -p -- "$_3X_WD"/workdir

# decide some important environment values
_3X_WD=$(readlink -f "$_3X_WD")
: ${_3X_RUN:=${_3X_WD#$_3X_ROOT/}}
export _3X_ROOT _3X_RUN _3X_WD
cd "$_3X_ROOT"

# prepare the assemble script
assembleScript=$(update-assembly-script)

# record environment variables
envVars=()
envFiles=("${_3X_RUN_ENVIRON:-$TOOLSDIR/runner/local/environ.default}")
if [ $(no-comments "${envFiles[@]}" | wc -l) -gt 0 ]; then
    envVarNames=$(list-var-names "${envFiles[@]}")
    msg +1 " recording environment as per ${envFiles[*]}: "$envVarNames
    {
        eval export -- $(no-comments "${envFiles[@]}" | sed 's/\([^=]*\)=\(.*\)/\1=${\1:-\2}/')
        for v in $envVarNames; do
            envVars+=("$v=${!v:-}")
        done
    } >/dev/null
fi

# assemble the inputs for experiment
msg "Assembling $_3X_RUN for $*"
"$assembleScript" "$_3X_WD" "$@" -- "${envVars[@]}" ||
    error "Assembly failed for $_3X_RUN"
