#!/usr/bin/env bash
# generate-assembly-script -- generate an experiment assembly script that
#                             reflects the logic of the given pattern
#                             directories
# Usage: generate-assembly-script PATTDIR...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -gt 0 ] || usage "$0" "No PATTDIR given"

shopt -s extglob
set -o braceexpand

codeForPatternDirs() {
    local nestingLevel=$((${depth:--1} + 1))
    local pattDir= patt= name=
    for pattDir; do
        [ -e "$pattDir" ] || continue
        echo "# $pattDir"
        case $pattDir in
            # measurements themselves need not any guards
            measure/+([^/]))
                name=${pattDir#measure/}
                checkIfNameIsSane "$name" "$pattDir"
                codeForMatchedPatternFile "$pattDir"
                continue
                ;;
        esac
        patt=$(basename "$pattDir")
        case $patt in
            *=?*)
                name=${patt%%=*}
                checkIfNameIsSane "$name" "$pattDir"
                echo "if [ x\"\${$name:-}\" = x'${patt#*=}' ]; then"
                codeForMatchedPatternFile "$pattDir"
                echo "fi"
                ;;
            *) # or *=)
                name=${patt%%=}
                checkIfNameIsSane "$name" "$pattDir"
                echo "case \${$name:-} in"
                for pattCaseFileOrig in "$pattDir"/*/ "$pattDir"/*.env; do
                    [ -e "$pattCaseFileOrig" ] || continue
                    pattCase=$(basename "$pattCaseFileOrig" .env)
                    pattCaseFile=${pattCaseFileOrig%/}
                    checkIfValueIsSane "$pattCase" "$name" "$pattCaseFileOrig"
                    echo "\"$pattCase\")"
                    codeForMatchedPatternFile "$pattCaseFile"
                    echo ";;"
                done
                if [[ $nestingLevel = 0 ]]; then
                    echo "*)"
                    echo "error \"$name\${$name:+=\${$name:-}} undefined\""
                    echo ";;"
                fi
                echo "esac"
                ;;
        esac
    done
}

codeForMatchedPatternFile() {
    local f=$1; shift
    if [ -d "$f" ]; then
        codeForSourcing "$f"/env
        echo import "$f"
        # look for nested pattern directories and generate code for them too
        codeForPatternDirs "$f"/*=*
    else
        codeForSourcing "$f"
        echo import "$f"
    fi
}

codeForSourcing() {
    local env=$1; shift
    if [ -r "$env" ]; then
        echo source "$env"
    fi
}

. "$TOOLSDIR"/sanity-checks.sh

codeForPatternDirs "$@"
