#!/usr/bin/env bash
# generate-assembly-script -- generate an experiment assembly script that
#                             reflects the logic of the given pattern
#                             directories
# Usage: generate-assembly-script PATTDIR...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -gt 0 ] || usage "$0" "No PATTDIR given"

shopt -s extglob
set -o braceexpand

codeForPatternDirs() {
    local nestingLevel=$((${depth:--1} + 1))
    local pattDir= patt= name=
    for pattDir; do
        [ -e "$pattDir" ] || continue
        echo "# $pattDir"
        patt=$(basename "$pattDir")
        case $patt in
            *=?*)
                name=${patt%%=*}
                echo "if [ x\"\${$name:-}\" = x'${patt#*=}' ]; then"
                codeForMatchedPatternFile "$pattDir"
                echo "fi"
                ;;
            *) # or *=)
                name=${patt%%=}
                echo "case \${$name:-} in"
                for pattCaseFile in "$pattDir"/*/ "$pattDir"/*.env; do
                    [ -e "$pattCaseFile" ] || continue
                    pattCase=$(basename "$pattCaseFile" .env)
                    pattCaseFile=${pattCaseFile%/}
                    echo "\"$pattCase\")"
                    codeForMatchedPatternFile "$pattCaseFile"
                    echo ";;"
                done
                if [[ $nestingLevel = 0 ]]; then
                    echo "*)"
                    echo "error \"$name=\$$name undefined\""
                    echo ";;"
                fi
                echo "esac"
                ;;
        esac
    done
}

codeForMatchedPatternFile() {
    local f=$1; shift
    if [ -d "$f" ]; then
        codeForSourcing "$f"/env
        echo import "$f"
        # look for nested pattern directories and generate code for them too
        codeForPatternDirs "$f"/*=*
    else
        codeForSourcing "$f"
        echo import "$f"
    fi
}

codeForSourcing() {
    local env=$1; shift
    if [ -r "$env" ]; then
        echo source "$env"
    fi
}

codeForPatternDirs "$@"
