#!/usr/bin/env bash
# generate-assembly-script -- generate an experiment assembly script that
#                             reflects the logic of the given pattern
#                             directories
# 
# > generate-assembly-script PATTDIR...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -gt 0 ] || usage "$0" "No PATTDIR given"

shopt -s extglob
set -o braceexpand

codeForPatternDirs() {
    local nestingLevel=$((${nestingLevel:--1} + 1))
    local pattDir= patt= name=
    for pattDir; do
        [ -d "$pattDir" ] || continue
        echo "# $pattDir"
        # handle some special cases
        case $pattDir in
            # program need not any guards
            program)
                codeForMatchedPatternDir "$pattDir"
                continue
                ;;
            # outputs themselves need not any guards
            output/+([^/]))
                name=${pattDir#output/}
                checkIfNameIsSane "$name" "$pattDir" || continue
                codeForMatchedPatternDir "$pattDir"
                continue
                ;;
        esac
        patt=$(basename "$pattDir")
        case $patt in
            *=?*)
                name=${patt%%=*}
                checkIfNameIsSane "$name" "$pattDir" || continue
                echo "if [ x\"\${$name:-}\" = x'${patt#*=}' ]; then" # NOTE no need to escape since it's a sane value
                codeForMatchedPatternDir "$pattDir"
                echo "fi"
                ;;
            *) # or *=)
                name=${patt%%=}
                checkIfNameIsSane "$name" "$pattDir" || continue
                echo "case \${$name:-} in"
                for pattCaseDirOrig in "$pattDir"/*/; do
                    [ -d "$pattCaseDirOrig" ] || continue
                    local pattCase=$(basename "$pattCaseDirOrig")
                    local pattCaseDir=${pattCaseDirOrig%/}
                    case $pattCase in *=*) continue ;; esac # skip nested pattern dirs
                    checkIfValueIsSane "$pattCase" "$name" "$pattCaseDirOrig" || continue
                    echo "'$pattCase')" # NOTE no need to escape since it's a sane value
                    codeForMatchedPatternDir "$pattDir"
                    codeForMatchedPatternDir "$pattCaseDir"
                    echo ";;"
                done
                if [[ $nestingLevel = 0 ]]; then
                    echo "*)"
                    echo "error \"$name\${$name:+=\${$name:-}} undefined\""
                    echo ";;"
                fi
                echo "esac"
                ;;
        esac
    done
}

codeForMatchedPatternDir() {
    local f=$1; shift
    codeForSourcing "$f"/env
    echo import "$f"
    # look for nested pattern directories and generate code for them too
    codeForPatternDirs "$f"/+([A-Za-z0-9@%:.+_-])=*
}

codeForSourcing() {
    local env=$1; shift
    if [ -r "$env" ]; then
        echo source "$env"
    fi
}

. "$TOOLSDIR"/sanity-checks.sh

echo '#!/usr/bin/env bash
# Usage: assemble.sh [INPUT_NAME=VALUE]... -- [ENV_NAME=VALUE]...
set -eu
be-quiet +3 || set -x

# create the directory to be assembled
_3X_ASSEMBLY_PRODUCT=$1; shift
mkdir -p -- "$_3X_ASSEMBLY_PRODUCT"/workdir
cp -f "$0" "$_3X_ASSEMBLY_PRODUCT"/assemble.sh
cd "$_3X_ASSEMBLY_PRODUCT"
unset _3X_ASSEMBLY_PRODUCT
trap "rm -f assembly.in-progress" EXIT
touch assembly.in-progress
: >assembly

# record and declare input parameters and environment variables
: >env; : >input; endOfInput=false
for param; do
    case $param in --) endOfInput=true; continue ;; esac
    declare -r "$param"
    echo "$param" >>env
    $endOfInput || echo "$param" >>input
done
unset param endOfInput


# define how each iteration of assembly works
assembly-iteration() {
'

codeForPatternDirs "$@"

echo '
}

# define/override some commands used in the assembly script
error() {
    echo "$*" >>assembly.error
    command error "$@"
}

source() {
    # replace source with our function that avoids any evaluation in the definitions
    local f=$1
    ! grep -qxF "${f%/env}" assembly || return 0
    local decl= v= l=1
    while read -r decl; do
        let l++
        decl=${decl%%*([ 	])#*}
        [ -n "$decl" ] || continue
        v=${decl%%=*}
        ! declare -p $v &>/dev/null || error "$f: line $l: $v: duplicate variable"
        export "$decl"
        declare -r $v
        _3X_ASSEMBLY_CONTINUE=true
    done <"$_3X_ROOT/$f"
}
import() {
    local path
    for path; do
        ! grep -qxF "$path" assembly || continue
        echo "$path" >>assembly
        _3X_ASSEMBLY_CONTINUE=true
        command import "$path"
    done
}

# repeat iterations until no change
_3X_ASSEMBLY_CONTINUE=true
while $_3X_ASSEMBLY_CONTINUE; do
    _3X_ASSEMBLY_CONTINUE=false
    assembly-iteration
done

# make sure all essential files exist
[ -x workdir/run ] || error "No executable \`run'\'' was assembled"
for f in env args stdin; do
    [ -e "$f" ] || touch "$f"
done

rm -f assembly.error
'
