#!/usr/bin/env bash
# import -- import an input directory
# Usage: EXPWD=OUTPUTDIR import INPUTDIR...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -gt 0 ]        || usage "$0" "At least one INPUTDIR must be given"
[ -n "${EXPWD:-}" ] || usage "$0" "EXPWD must be defined"

# TODO check if cp is GNU coreutil's
cpopts=
be-quiet +1 || cpopts+=--verbose

for path in "$@"; do
    if ! grep -q "^$path$" "$EXPWD"/assembly.order; then
        msg " importing $path"
        echo "$path" >>"$EXPWD"/assembly.order
        if [ -d "$path" ]; then
            # a directory containing files and nested patterns
            # copy files
            find "$path" ! \( -name '*=*' -prune -o -type d -o \
                -name env -o -name args -o -name +args -o -name args+ \
                \) |
            xargs cp $cpopts --archive --link --target-directory="$EXPWD"/ |
            sed 's/^/  linking /'
            # environment
            if [ -r "$path"/env ]; then
                msg +1 "  appending $path/env"
                cat "$path"/env >>"$EXPWD"/env
            fi
            # command-line arguments
            for a in "$path"/{args,+args,args+}; do
                if [ -r "$a" ]; then
                    case ${a##*/} in
                        args) # replace arguments
                            cp $cpopts --no-clobber "$a" "$EXPWD"/args |
                            sed 's/^/  linking /'
                            ;;
                        args+) # append arguments
                            msg +1 "  appending $a"
                            cat "$a" >>"$EXPWD"/args
                            ;;
                        +args) # prepend arguments
                            msg +1 "  prepending $a"
                            if [ -z "${tmp:-}" ]; then
                                tmp=$(mktemp /tmp/expkit-import.XXXXXX)
                                trap "rm -f $tmp" EXIT
                            fi
                            cat "$a" "$EXPWD"/args >$tmp
                            cat $tmp >"$EXPWD"/args
                            ;;
                    esac
                fi
            done
        else
            # .env files
            if [ -r "$path" ]; then
                cat "$path" >>"$EXPWD"/"${path##*.}"
            fi
        fi
    fi
done
