#!/usr/bin/env bash
# update-assembly-script -- update the assembly script if necessary
# 
# > update-assembly-script
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-31
set -eu

. find-run-archive.sh
cd "$_3X_ROOT"

let SHLVL--
update-assembly-script() {
    local scpt=$1; shift
    if ! [ -s "$scpt" ] ||
        [ input -nt "$scpt" -o output -nt "$scpt" -o program -nt "$scpt" ] ||
        find "$0" $(type -p generate-assembly-script) \
            "$DATADIR"/assembler/execute.sh "$@" -newer "$scpt" | read; then
        touch "$scpt"
        msg "Updating $scpt"
        local tmp=$(mktemp "$scpt".XXXXXX)
        trap "rm -f $tmp" EXIT
        generate-assembly-script "$@" >"$tmp"
        chmod +x "$tmp"
        mv -f "$tmp" "$scpt"
        trap - EXIT
    fi
}
update-assembly-script "$_3X_ASSEMBLE" program input/?*=* output/*
echo "$_3X_ASSEMBLE"
