#!/usr/bin/env bash
# update-assembly-script -- update the assembly script if necessary
# 
# > update-assembly-script
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-31
set -eu

_3X_ROOT=$(3x-findroot)
cd "$_3X_ROOT"

let SHLVL--
update-assembly-script() {
    local scpt=$1; shift
    if ! [ -s "$scpt" ] ||
        [ input -nt "$scpt" -o output -nt "$scpt" -o program -nt "$scpt" ] ||
        find "$0" $(type -p generate-assembly-script) "$@" -newer "$scpt" | read; then
        msg "Updating $scpt"
        local tmp=$(mktemp "$scpt".XXXXXX)
        trap "rm -f $tmp" EXIT
        generate-assembly-script "$@" >"$tmp"
        chmod +x "$tmp"
        { vim -u NONE -i NONE -N -n -e -s "$tmp" &>/dev/null || true; } <<-EOF
	source \$VIMRUNTIME/vimrc_example.vim
	set ft=sh nobackup
	norm gg=G
	wq!
	EOF
        mv -f "$tmp" "$scpt"
        trap - EXIT
    fi
}
assembleScript=.3x/assemble.sh
update-assembly-script $assembleScript program input/?*=* output/*
echo $assembleScript
