#!/usr/bin/env bash
# exp-inputs -- enumerate input variables
# Usage: exp inputs [-v] [NAME]...
# 
# Enumerates all available input variables.  If a NAME is given, it checks
# if the variable is defined and enumerates.
# 
# Specify -v if you want to enumerate the possible values for each name as well.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-07
set -eu
shopt -s extglob

# process options
enumValues=false
while getopts "v" opt; do
    case $opt in
        v)
            enumValues=true
            ;;
    esac
done
shift $(($OPTIND - 1))


# setup environment
EXPROOT=$(exp-findroot)
export EXPROOT
cd "$EXPROOT"

# prepare pattern directories to show
if [ $# -eq 0 ]; then
    # default is to show all input variables
    set -- program input/[A-Za-z_]*([A-Za-z0-9_])=
else
    # map each input name to pattern directory
    args=()
    for name in "$@"; do
        if [[ $name == "program" ]]; then
            path=program
        else
            path=input/$name=
        fi
        [ -d "$path" ] || error "Undefined input: $name"
        args+=("$path")
    done
    set -- "${args[@]}"
fi

# finally, show them with values when necessary
if $enumValues; then
    showInput() {
        local name=$1
        local pattDir=$2
        local values=$(
            cd "$pattDir"
            find +([A-Za-z0-9@%:.+_-])/env -maxdepth 0 2>/dev/null | sort -g |
            while read -r path; do
                [ -e "$path" ] || continue
                echo -n ",$(basename "${path%/env}")"
            done
        )
        values=${values#,}
        echo "$name=$values"
    }
else
    showInput() { echo "$1"; }
fi
for path in "$@"; do
    [ -e "$path" ] || continue
    name=$(basename "$path")
    name=${name%%=*}
    showInput $name "$path"
done
