#!/usr/bin/env bash
# normalize-inputs -- normalize input specification
# 
# > normalize-inputs -[nvp] [NAME[=VALUE[,VALUE]...]]...
# > normalize-inputs -[nvp] DIR...
# 
# In addition to the obvious NAME=VALUE pairs, this also understands paths both
# relative and absolute to either input variables or values of input
# variables under the $_3X_ROOT, so you can rely on shell's file path completion.
# 
# Specify -n option to prepend any missing NAME.
# Specify -v to attach possible values for each NAME without any VALUE as well.
# Specify -p to pass thru any unrecognized argument. Otherwise, it will cause an error.
# 
# For processing arguments to a script, use as follows:
# > args=($(normalize-inputs "$@"))
# > [ ${#args[@]} -eq 0 ] && set -- || set -- "${args[@]}"
# 
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-07
set -eu

# process options
fillNames=false
fillValues=false
passUnrecognized=false
while getopts "nvp" opt; do
    case $opt in
        n)
            fillNames=true
            ;;
        v)
            fillValues=true
            ;;
        p)
            passUnrecognized=true
            ;;
    esac
done
shift $(($OPTIND - 1))

[ $# -gt 0 ] || exit 0

_3X_ROOT=$(3x-findroot)

## normalize command-line arguments
args=()
restArgs=()
for cond in "$@"; do
    if [ -e "$cond" ]; then # infer input name/value from path names
        # e.g., input/x=/1 input/x=/2.env input/y=abcd input/z=/
        #    -> x={1,2} y=abcd z
        cond=$(readlink -f "$cond")
        cond=${cond#$_3X_ROOT/}
        case $cond in
            input/*=*)
                name=${cond#input/}
                name=${name%%=*}
                value=${cond#input/$name=}
                value=${value#/}
                value=${value%%/*}
                args+=("$name=$value")
                ;;
            *)
                error "$cond: Unrecognized input path"
                ;;
        esac
    else # or, sanitize cond
        # see if it's a valid input
        name=${cond%%=*}
        pattDir="$_3X_ROOT"/input/$name=
        if ! [ -d "$pattDir" ]; then
            if $passUnrecognized; then
                # hold unrecognized arguments for output
                restArgs+=("$cond")
                continue
            else
                error "$cond: Undefined input name"
            fi
        fi
        valuePart=${cond#$name}
        valuePart=${valuePart#=}
        if [ -n "$valuePart" ]; then
            values=
            OIFS=$IFS
            IFS=,
            values=($valuePart)
            IFS=$OIFS
            for value in "${values[@]}"; do
                [ -d "$pattDir/$value" ] ||
                    error "$name=$value: Undefined input value"
            done
        fi
        args+=("$name=$valuePart")
    fi
done
[ ${#args[@]} -gt 0 -o ${#restArgs[0]} -gt 0 ] || exit 0
[ ${#args[@]} -eq 0 ] && set -- || set -- "${args[@]}"

# group by var names
eval "set -- $(coalesce-values-by-name = , "$@")"

# all the variables must be there, so prefix them
if $fillNames; then
    arg-has() {
        local name=$1 arg=; shift
        for arg; do
            [[ $arg =~ $name ]] || continue
            return 0
        done
        return 1
    }
    args=()
    for name in $(3x-inputs); do
        arg-has "^$name(=.*)?$" "$@" || args+=("$name"=)
    done
    [ ${#args[@]} -eq 0 ] || set -- "${args[@]}" "$@"
fi

# fill possible values for names with empty ones
if $fillValues; then
    args=()
    for cond in "$@"; do
        name=${cond%%=*}
        values=${cond#$name=}
        [ -n "$values" ] || cond=$(3x-inputs -v "$name")
        args+=("$cond")
    done
    [ ${#args[@]} -gt 0 -o ${#restArgs[0]} -gt 0 ] || exit 0
    [ ${#args[@]} -eq 0 ] && set -- || set -- "${args[@]}"
fi

# append any unrecognized arguments
! $passUnrecognized || [ ${#restArgs[@]} -eq 0 ] || set -- "$@" "" "${restArgs[@]}"

# output the normalized arguments, so it can be used in the following manner:
#   set -- $(normalize-inputs "$@")
for arg in "$@"; do
    # TODO escape whitespace?
    echo "$arg"
done |
sort -g # normalize ordering
