#!/usr/bin/env bash
# queue-refresh -- refresh current queue records of its state
# 
# > . find-runner.sh -
# > setsid queue-refresh
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-01
set -eu
. runner.sh

# check lock handles to see if there's anything alive
for handle in $WORKER_LOCK_PREFIX*.lock $RUNDIR_PREFIX*/lock; do
    [ -e "$handle" ] || continue
    lockproc "$handle" alive || continue
    exit
done

# otherwise, remove the flag
rm -f $ACTIVE_FLAG
