#!/usr/bin/env bash
# > 3x start
# Starts executing runs in current queue.
#
# queue-start -- start execution of runs in current queue
# 
# > . find-runner.sh -
# > setsid queue-start
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-02-16
set -eu

error "$_3X_RUNNER/queue-start: Not implemented"
