#!/usr/bin/env bash
# base.async/refresh-all -- check the state of all runs that have been scheduled
# > refresh-all _3X_WORKER_DIR
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-03-05
error "$_3X_RUNNER/refresh-all: Not implemented"
