#!/usr/bin/env bash
# base.async/start-all -- schedule all runs
# > start-all _3X_WORKER_DIR
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-03-05
error "$_3X_RUNNER/start-all: Not implemented"
