#!/usr/bin/env bash
# exp-define -- Define element of the experiment
# Usage: exp define WHAT NAME HOW...
#        exp define program  NAME COMMAND...
#        exp define input    NAME[:TYPE] VALUE1 [VALUE2]...
#        exp define output   NAME[:TYPE] extract  REGEXP_BEFORE  REGEXP  REGEXP_AFTER
#        exp define output   NAME:TYPE   file     FILENAME
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-24
set -eu

EXPROOT=$(exp-findroot)
export EXPROOT

[ $# -gt 0 ] || usage "$0" "WHAT to define is missing"
What=$1; shift

[ $# -gt 0 ] || usage "$0" "NAME is missing"
Name=$1; shift

. "$TOOLSDIR"/sanity-checks.sh

# TODO expand glob pattern in any arguments?

cd "$EXPROOT"

case $What in
    program)
        dir="program/$Name"
        checkIfValueIsSane "$Name" program "$dir"
        mkdir -p "$dir"
        touch "$dir"/env
        {
            echo "#!/usr/bin/env bash"
            for Command; do
                echo "$Command"
            done
        } >"$dir"/run
        chmod +x "$dir"/run
        ;;

    input)
        extractTypeFromName nominal # TODO default is nominal, but may we can try recognition
        dir="input/$Name="
        checkIfNameIsSane "$Name" "$dir"
        for Value; do
            checkIfValueIsSane "$Value" "$Name" "$dir/$Value"
        done
        for Value; do
            checkIfNameIsSane "$Name" "$Name"
            vdir="$dir/$Value"
            mkdir -p "$vdir"
            touch "$vdir"/env
        done
        echo "$Type" >"$dir"/datatype
        # TODO decide what to do with the other ones not mentioned
        ;;

    output)
        outputType=${1:-}; shift || true
        extractTypeFromName ratio # default is ratio
        dir="output/$Name"
        checkIfNameIsSane "$Name" "$dir"
        case $outputType in 
            extract)
                [ $# -gt 0 ] || usage "$0" "Missing REGEXP_BEFORE"
                [ $# -gt 1 ] || usage "$0" "Missing REGEXP"
                [ $# -eq 3 ] || usage "$0" "Missing REGEXP_AFTER"
                mkdir -p "$dir"
                {
                    echo "#!/usr/bin/env bash"
                    echo "cat stdout stderr |"
                    echo -n "extract-regexp "; escape-args-for-shell "$@"
                } >"$dir"/measure
                ;;
            file)
                [ $# -eq 1 ] || usage "$0" "Missing FILENAME"
                mkdir -p "$dir"
                {
                    echo "#!/bin/sh"
                    echo -n "echo "; escape-args-for-shell "$1"
                } >"$dir"/measure
                ;;
            *)
                usage "$0" "Unknown output type $outputType"
                ;;
        esac
        chmod +x "$dir"/measure
        echo "$Type" >"$dir"/datatype
        ;;
esac
