#!/usr/bin/env bash
# 3x-history -- Display history of the current queue
# Usage: 3x status
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-14
set -eu

. "$TOOLSDIR"/find-queue-runner.sh

cd "$queueDir"

# TODO add CLI switch to selectively show DONE/RUNNING/PLANNED

{
    PREFIXPATT='^3x[[:space:]][[:space:]]*run[[:space:]][[:space:]]*'

    # runs already finished
    if [ -r done ]; then
        sed "s:$PREFIXPATT:DONE :" <"done"
    fi

    # runs running now
    if [ -r running ]; then
        sed "s:$PREFIXPATT:RUNNING :" <running
    fi

    # runs planned
    if [ -r plan ]; then
        sed "s:$PREFIXPATT:PLANNED :; s:$: ?:" <plan
    fi
} | column -t
