#!/usr/bin/env bash
# 3x-reset -- stop executing current queue and revert to a clean state
# 
# > 3x reset -h
# Shows this usage.  Usage varies for different types of target.
# 
# > 3x reset
# Stops executing runs of current queue from all targets and revert queue
# records to a clean state without any intermediate data for RUNNING or ABORTED
# runs.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-08-22
set -eu

while getopts "h" o; do
    case $o in
        h)
            usage "$0"
            exit
            ;;
    esac
done
shift $(($OPTIND - 1))

. find-queue.sh

# first, stop executions for current queue
3x-stop

# then synchronize queue records with whats actually there
for-every-runner setsid queue-sync

# revert any remaining ABORTED runs to PLANNED
cd "$_3X_ROOT"
set +e
queue list-only runId  "state#"=ABORTED | xargs unarchive "$_3X_ARCHIVE" 2>/dev/null
queue list-only runId  "state#"=ABORTED | xargs rm -rf --
queue list-only serial "state#"=ABORTED | xargs queue mark-as PLANNED
