#!/usr/bin/env bash
# 3x-stop -- stop executing the current queue
# 
# > 3x stop
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-17
set -eu

. find-queue.sh
cd "$queueDir"

# we need to call queue-stop for all runners that were running
export queue queueDir
OPATH=$PATH
for stop in "$queueRunner"/*/queue-stop; do
    [ -x "$stop" ] || continue
    PATH="$(dirname "$stop"):$PATH"
    setsid "$stop" "$@"
    PATH=$OPATH
done
