#!/usr/bin/env bash
# 3x-status -- display status of current queue
# 
# > 3x status
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-14
set -eu

. find-runner.sh -

# TODO add CLI switch to selectively show DONE/RUNNING/PLANNED

{
    # runs already finished
    cat done 2>/dev/null || true

    # runs running now
    cat running 2>/dev/null || true

    # runs planned
    if [ -r plan ]; then
        serialOnEachLine plan $(( $(cat .count 2>/dev/null || echo 0) + 1 )) |
        sed 's:^run[[:space:]][[:space:]]*:PLANNED :'
    fi
} | column -t
