#!/usr/bin/env bash
# 3x-start -- start executing runs in the current queue at the target
# 
# > 3x start
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-07
set -eu

. find-queue-runner.sh

cd "$queueDir"
export queue queueDir target targetDir

# mark as running
{
    date +"# %FT%T%:z"
    echo "start $*"
} >>started

# start queue runner in a separate process group, so we can kill all related
# processes together later.
exec setsid queue-start "$@"
