#!/usr/bin/env bash
# 3x-start -- start executing runs in current queue at its target
# 
# > 3x start -h
# Shows this usage.  Usage varies for different types of target.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-07
set -eu

while getopts "h" o; do
    case $o in
        h)
            usage "$0"
            (
                . find-runner.sh -
                usage "$(type -p queue-start)"
            ) 2>/dev/null ||
                usage - <<-EOF
		#
		# > 3x start
		# Starts executing runs in current queue at its target.
		#
		EOF
            exit
            ;;
    esac
done
shift $(($OPTIND - 1))

# TODO accept number of concurrent workers

# make sure the assemble script is up to date
assembleScript=$(update-assembly-script)

# start queue runner in a separate process group, so we can kill all related
# processes together later.
. find-runner.sh -
exec setsid queue-start "$@"
