#!/usr/bin/env bash
# 3x-stop -- stop executing current queue
# 
# > 3x stop -h
# Shows this usage.  Usage varies for different types of target.
# 
# > 3x stop
# Stops executing runs of current queue from all targets.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-17
set -eu

while getopts "h" o; do
    case $o in
        h)
            usage "$0"
            (
                . find-runner.sh -
                usage "$(type -p queue-stop)"
            ) 2>/dev/null ||
                true
            exit
            ;;
    esac
done
shift $(($OPTIND - 1))

. find-queue.sh

if [ $# -eq 0 ]; then
    # we need to call queue-stop for all active runners
    for-each-active-runner queue-stop
else # if there are given arguments, just stop the current target
    . find-runner.sh -
    setsid queue-stop "$@"
fi
