#!/usr/bin/env bash
# exp-run -- run an experiment with given parameters
# Usage: exp run PROGRAM [NAME=VALUE]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -ge 1 ] || usage "$0" "At least the PROGRAM to run must be given"

: ${EXPROOT:=$(exp-findroot)}
: ${EXPRUNID:=$(date +run/%Y/%m/%d/%H%M%S.%N."$program")}
export EXPROOT EXPRUNID EXPWD="$EXPROOT/$EXPRUNID"

program=$1; shift
program=$(basename "$program")

# create a working directory for this experiment ($EXPWD)
mkdir -p "$EXPWD"

# assemble it for running and measurement
exp-assemble "$EXPWD" program="$program" "$@"

# run it
msg "Running $EXPRUNID with $*"
cd "$EXPWD"
set -m
env - \
    PATH="$TOOLSDIR:$(dirname $(type -p sed)):$(dirname "$SHELL")" \
    EXPKIT_HOME="$EXPKIT_HOME" \
    EXPKIT_LOGLVL="$EXPKIT_LOGLVL" \
    EXPROOT="$EXPROOT" \
    EXPWD="$EXPWD" \
    EXPRUNID="$EXPRUNID" \
    record-run &
runpid=$!
set +m

# watch stdout and stderr
trap "kill -TERM -$runpid; wait" INT
tail -qF stdout --pid=$runpid      2>/dev/null &
tail -qF stderr --pid=$runpid 1>&2 2>/dev/null &
wait || true

exitcode=$(cat exitcode 2>/dev/null || echo 127)
msg "Finished $EXPRUNID with exitcode $exitcode"

# run measurements
for mx in exp.measure/*/measure; do
    m=$(basename "$(dirname "$mx")")
    if [ -x "$mx" ]; then
        # TODO under the same env
        echo "$m=$("$mx")"
    fi
done >exp.outcome

exit $exitcode
