#!/usr/bin/env bash
# exp-run -- run an experiment with given parameters
# Usage: exp run PROGRAM [NAME=VALUE]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
set -eu

[ $# -ge 1 ] || usage "$0" "At least the PROGRAM to run must be given"

program=$1; shift
program=$(basename "${program%+(/)}")
export EXPROOT=$(exp-findroot)

# create a working directory for this experiment ($EXPWD)
export EXPRUNID=$(date +runs/%Y/%m/%d/%H%M%S."$program")
export EXPWD="$EXPROOT/$EXPRUNID"
mkdir -p "$EXPWD"

# assemble it
exp-assemble "$EXPWD" program="$program" "$@"

# run it
msg "Running $EXPRUNID with $*"
cd "$EXPWD"
env - \
    EXPKIT_HOME="$EXPKIT_HOME" \
    EXPKIT_LOGLVL="$EXPKIT_LOGLVL" \
    EXPWD="$EXPWD" \
    EXPRUNID="$EXPRUNID" \
    PATH="$TOOLSDIR:$(dirname $(type -p sed)):$(dirname "$SHELL")" \
    record-run &
runpid=$!

# watch stdout and stderr
tail -qF stdout --pid=$runpid 2>/dev/null &
tail -qF stderr --pid=$runpid 1>&2 2>/dev/null
wait

# TODO run measurement
