#!/usr/bin/env bash
# new-run-id -- generate a new id for _3X_RUN
set -eu
fmt=$(
    fmtConf="$_3X_ROOT/.3x/run-id-format"
    [ -s "$fmtConf" ] && cat "$fmtConf" ||
        echo run/%Y/%m%d/%H/%M%S.%N
)
exec date +"$fmt"
