#!/usr/bin/env bash
# record-run -- run the run.sh script while recording its behavior
# Usage: cd $EXPWD && record-run
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-05
set -u

eval "
be-quiet +5 || set -x
$(cat ./env | sed "s/'/'\\''/g; s/^/export '/; s/$/'/")
"

eval "cmd=(
./run
$(cat args)
)"

(
be-quiet +1 || set -x
cd "$EXPWD"
"${cmd[@]}" <stdin >stdout 2>stderr
)
echo $? >exitcode
