#!/usr/bin/env bash
# queue-changed -- handle the event of queue modification
# 
# > . find-queue-runner.sh
# > setsid queue-changed
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-17
set -eu

. find-queue.sh
. local-runner.sh

cd "$queueDir"

queue-refresh

if queue-is-active; then

    for workerHandle in $WORKER_LOCK_PREFIX-*.lock; do
        [ -e "$workerHandle$WORKER_WAITING_SUFFIX" ] || continue
        # wake up a waiting worker for the queue change
        lockproc $workerHandle kill -$WORKER_WAITING_SIGNAL
    done

fi
