#!/usr/bin/env bash
# queue-sync -- synchronize the current queue records with reality
# 
# > . find-queue-runner.sh
# > setsid queue-sync
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-07
set -eu

. local-runner.sh

cd "$queueDir"

clean-stale-running-dirs() {
    # determine the stopped/stale ones
    set --
    for runDir in $RUNDIR_PREFIX*/; do
        runDir=${runDir%/}
        lockproc $runDir/lock alive || set -- "$@" $runDir
    done

    # clean up stale runDirs
    for staleRunDir; do
        [ -e "$staleRunDir" ] || continue

        serial=${staleRunDir#$RUNDIR_PREFIX}
        msg +2 "moving $queue #$serial back to plan"

        # unregister from queue's running list
        {
            echo "g/ #$serial /d"
            echo wq
        } | ed running >/dev/null

        # move it back to plan
        {
            echo "0r $staleRunDir/cmdln"
            echo wq
        } | ed plan >/dev/null

        # and remove
        ! [ -e $staleRunDir/run/ ] || unarchive "$_3X_ARCHIVE" $staleRunDir/run/
        ! [ -e runs/$serial/     ] || unarchive "$_3X_ARCHIVE" runs/$serial/
        rm -rf $staleRunDir runs/$serial/ runs/$serial
    done
}
synchronized running.lock  clean-stale-running-dirs

# then, reflect the queue state
queue-refresh
