#!/usr/bin/env bash
# queue-stop -- Stop executing locally
# Usage: . find-queue-runner.sh; cd "$queueDir"; queue-stop [WORKER]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-17
set -eu

# collect the handles of workers
if [ $# -gt 0 ]; then
    handles=()
    for workerId; do
        handle=worker-"$workerId".lock
        [ -e "$handle" ] || error "No such worker #$workerId" || continue
        handles+=("$handle")
    done
    set -- "${handles[@]}"
else
    set -- worker-*.lock running.*/lock
fi

# and stop the workers
for handle; do
    [ -e "$handle" ] || continue
    lockproc "$handle" kill
done
