#!/usr/bin/env bash
# queue-changed -- handle the event of queue modification
# 
# > . find-queue-runner.sh
# > setsid queue-changed
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-01-17
set -eu

. local-runner.sh

cd "$queueDir"

queue-refresh

if queue-is-alive; then

    # start a worker for the queue if none
    queue-start &

fi
