#!/usr/bin/env bash
# queue-stop -- stop executing locally
# 
# > . find-queue-runner.sh
# > setsid queue-stop [WORKER]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-17
set -eu

. local-runner.sh

cd "$queueDir"

# collect the handles of workers
if [ $# -gt 0 ]; then
    handles=()
    for workerId; do
        handle=$WORKER_LOCK_PREFIX-"$workerId".lock
        [ -e "$handle" ] || error "No such worker #$workerId" || continue
        handles+=("$handle")
    done
    set -- "${handles[@]}"
else
    set -- $WORKER_LOCK_PREFIX-*.lock $RUNDIR_PREFIX*/lock
fi

# and stop the workers
for handle; do
    [ -e "$handle" ] || continue
    lockproc "$handle" kill
done

# then synchronize queue records with reality
queue-sync
