#!/usr/bin/env bash
#
# local/target-info -- display local target info
# > target-info TARGET
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-06-26
set -eu

code=0

super "$0" "$@" || code=$?
echo

Target=$1
cd "$_3X_ROOT"/run/target/"$Target"

echo "# environ (environment variables):"
cat environ 2>/dev/null || true
echo

echo "# description:"
echo "Execute runs on local machine under"
diff-environ

exit $code
