#!/usr/bin/env bash
# > 3x target TARGET define local [NAME[=VALUE]]...
# Defines a new local execution environment, named TARGET.  Specified NAMEs are
# the names of variables you want to pass down to the environment used for
# executing planned runs.  Additionally, a fixed, predefined VALUE can be
# specified for a variable.
#
#
# local/target-define -- define a local target
# > _3X_ROOT=... \
# > _3X_RUNNER=... \
# > target-define TARGET [NAME[=VALUE]]...
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-06-26
set -eu

super "$0" "$@"

. runner.sh

Target=$1; shift
export _3X_TARGET=$Target
export _3X_TARGET_DIR="$_3X_ROOT"/run/target/"$Target"

cd "$_3X_TARGET_DIR"

# replace the environment configuration
create-backup-candidate environ
if [ $# -gt 0 ]; then
    for nameValuePair; do
        echo $nameValuePair
    done >environ
else # use default configuration if none given
    cp -f "$(findOneInTargetOrRunners environ)" environ
fi
keep-backup-if-changed environ
