#!/usr/bin/env bash
#
# ssh/target-info -- display remote (ssh) target info
# > target-info TARGET
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-13
set -eu
. remote-runner.sh

code=0

super "$0" "$@" || code=$?
echo

Target=$1
cd "$_3X_ROOT"/run/target/"$Target"

echo "# remote (remote URL):"
remote=$(cat remote 2>/dev/null) || code=2
echo "$remote"
echo

echo "# environ (environment for execution):"
cat environ 2>/dev/null || code=2
echo

parseRemote $remote
echo "# description:"
echo "Execute runs via ssh at \`${remoteUser:+$remoteUser@}$remoteHost\`, using "
echo "directory \`$remoteRoot\` for temporary storage, under"
diff-environ

exit $code
