#!/usr/bin/env bash
#
# ssh/target-info -- display remote (ssh) target info
# > target-info TARGET
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-07-13
set -eu

code=0

super "$0" "$@" || code=$?
echo

Target=$1
cd "$_3X_ROOT"/run/target/"$Target"

echo "# remote (remote URL):"
cat remote 2>/dev/null || code=2
echo

echo "# environ (environment for execution):"
cat environ 2>/dev/null || code=2

exit $code
